
[package]
name = "ivo-types"
license-file = "../../../LICENSE"
publish = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "These are type definitions for the ivo crate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
futures-locks = "0.7"
