[package]
name = "ivo"
version = "0.0.1"
edition = "2021"
description = "The schema valitator that brings user stories to life, inspired by ivo on npm"
license-file = "../../LICENSE"
keywords = ["schema", "validation"]
homepage = "https://github.com/kamtoeddy/ivo#readme"
repository = "https://github.com/kamtoeddy/ivo.git"

[features]
validators = ["dep:ivo_validators"]

[dependencies]
chrono = "0.4"
futures = "0.3"
ivo_struct = { path = "../ivo_struct" }
ivo_validators = { path = "../ivo_validators", optional = true}
