[package]
name = "ivo_validators"
license-file = "../../../LICENSE"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "optional built-in validators for ivo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
regex = "1.10"
