
[package]
name = "ivo-derive"
license-file = "../../../LICENSE"
publish = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Proc-macro crate for #[derive(IvoStruct)] — part of ivo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
ivo-types = { path = "../ivo-types", version = "0.0.2" }
proc-macro2 = "1"
proc-macro-crate = "3.1"
quote = "1.0"
syn = { version = "2.0.118", features = ["full"] }
