[workspace]
members = ["crates/*", "demos"]
resolver = "2"

[workspace.package]
version = "0.0.2"
edition = "2021"
authors = ["kamtoeddy <lollipopkalog@gmail.com>"]
license-file = "../LICENSE"
repository = "https://github.com/kamtoeddy/ivo/rs"
homepage = "https://github.com/kamtoeddy/ivo/rs"
keywords = ["schema", "validation"]
categories = ["encoding", "parsing"]
rust-version = "1.80.0"

[workspace.dependencies]
futures-locks = "0.7"
