[package]
name = "ivo"
license-file = "../../../LICENSE"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "The schema valitator that brings user stories to life, inspired by ivo on npm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
validators = ["dep:ivo_validators"]

[dependencies]
futures = "0.3"
futures-locks = "0.7"
ivo_derive = { path = "../ivo_derive" }
ivo_validators = { path = "../ivo_validators", optional = true}
