[package]
name = "ivo"
publish = true
description = "The rust implementation of the ivo schema valitator"
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true
autotests = false

[[test]]
name = "mod"
path = "tests/mod.rs"

[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"
authors = ["kamtoeddy <kamtoeddytagne@gmail.com>"]
categories = ["data-structures", "development-tools"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/kamtoeddy/ivo"
homepage = "https://ivo.kamtoeddy.com/docs/rs"
keywords = ["ivo", "schema", "validation", "data-modelling"]
rust-version = "1.85.0"

[workspace.dependencies]
ivo-derive = { path = "crates/derive", version = "0.5.0" }

[dependencies]
ivo-derive = { path = "./crates/derive", version = "0.5.0" }

[dev-dependencies]
async-std = { version = "1.0", features = ["attributes"] }
paste = "1"
smol = "1.3"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }

[[example]]
name = "constants"
path = "examples/constants.rs"

[[example]]
name = "dependent_defaults"
path = "examples/dependent_defaults.rs"

[[example]]
name = "dependent_on_dependent"
path = "examples/dependent_on_dependent.rs"

[[example]]
name = "dependent_readonly"
path = "examples/dependent_readonly.rs"

[[example]]
name = "lax_defaults"
path = "examples/lax_defaults.rs"

[[example]]
name = "lax_with_validators"
path = "examples/lax_with_validators.rs"

[[example]]
name = "lax_readonly"
path = "examples/lax_readonly.rs"

[[example]]
name = "lax_required"
path = "examples/lax_required.rs"

[[example]]
name = "lax_with_ignore"
path = "examples/lax_with_ignore.rs"

[[example]]
name = "lax_with_ignore_init"
path = "examples/lax_with_ignore_init.rs"

[[example]]
name = "lax_with_ignore_update"
path = "examples/lax_with_ignore_update.rs"

[[example]]
name = "virtuals_with_alias_name"
path = "examples/virtuals_with_alias_name.rs"

[[example]]
name = "virtuals_with_alias_name_same_as_dependent"
path = "examples/virtuals_with_alias_name_same_as_dependent.rs"
