[package]
name = "ivo"
publish = true
description = "The rust implementation of the ivo schema valitator"
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
rust-version.workspace = true
autotests = false

[[test]]
name = "mod"
path = "tests/mod.rs"

[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
version = "0.5.0"
edition = "2021"
authors = ["kamtoeddy <kamtoeddytagne@gmail.com>"]
categories = ["data-structures", "development-tools"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/kamtoeddy/ivo"
homepage = "https://ivo.kamtoeddy.com/docs/rs"
keywords = ["ivo", "schema", "validation", "data-modelling"]
rust-version = "1.85.0"

[features]
validators = ["dep:ivo-validators"]

[workspace.dependencies]
# examples & tests deps
async-lock = "3"
async-std = { version= "1.13.2", features = ["attributes"] }
chrono = "0.4.45"
regex = "1.10"
unicode-normalization = "0.1"

[dependencies]
async-lock.workspace = true
ivo-derive = { path = "./crates/derive", version = "0.5.0" }
ivo-validators = { path = "./crates/validators", version = "0.5.0", optional = true}

[dev-dependencies]
async-std = { workspace = true, features = ["attributes"] }
chrono.workspace = true
paste = "1"
regex.workspace = true
seahash = "4.1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
smol = "1.3"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros"] }
trybuild = "=1.0.119"
unicode-normalization.workspace = true

[[example]]
name = "constants"
path = "examples/constants.rs"

[[example]]
name = "dependent_defaults"
path = "examples/dependent_defaults.rs"

[[example]]
name = "dependent_on_dependent"
path = "examples/dependent_on_dependent.rs"

[[example]]
name = "dependent_readonly"
path = "examples/dependent_readonly.rs"

[[example]]
name = "lax_defaults"
path = "examples/lax_defaults.rs"

[[example]]
name = "lax_with_validators"
path = "examples/lax_with_validators.rs"

[[example]]
name = "lax_readonly"
path = "examples/lax_readonly.rs"

[[example]]
name = "lax_required"
path = "examples/lax_required.rs"

[[example]]
name = "lax_with_ignore"
path = "examples/lax_with_ignore.rs"

[[example]]
name = "lax_with_ignore_init"
path = "examples/lax_with_ignore_init.rs"

[[example]]
name = "lax_with_ignore_update"
path = "examples/lax_with_ignore_update.rs"

[[example]]
name = "virtuals_with_alias_name"
path = "examples/virtuals_with_alias_name.rs"

[[example]]
name = "virtuals_with_alias_name_same_as_dependent"
path = "examples/virtuals_with_alias_name_same_as_dependent.rs"

[[example]]
name = "virtuals_with_required"
path = "examples/virtuals_with_required.rs"

[[example]]
name = "option_on_success"
path = "examples/option_on_success.rs"

[[example]]
name = "required"
path = "examples/required.rs"

[[example]]
name = "required_error"
path = "examples/required_error.rs"

[[example]]
name = "required_readonly"
path = "examples/required_readonly.rs"

[[example]]
name = "required_with_ignore_update"
path = "examples/required_with_ignore_update.rs"

[[example]]
name = "required_with_re_validate"
path = "examples/required_with_re_validate.rs"

[[example]]
name = "timestamps_with_default_names"
path = "examples/timestamps_with_default_names.rs"

[[example]]
name = "main_demo"
path = "examples/main_demo/src/main.rs"
required-features = ["validators"]

[[example]]
name = "timestamps_with_custom_names"
path = "examples/timestamps_with_custom_names.rs"

[[example]]
name = "virtuals"
path = "examples/virtuals.rs"

[[example]]
name = "virtuals_with_ignore"
path = "examples/virtuals_with_ignore.rs"

[[example]]
name = "virtuals_with_ignore_init"
path = "examples/virtuals_with_ignore_init.rs"

[[example]]
name = "virtuals_with_ignore_update"
path = "examples/virtuals_with_ignore_update.rs"
