
[package]
name = "ivo-validators"
publish = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Optional built-in validators for ivo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
regex.workspace = true
