[package]
name = "ivo"
description = "Ivo v2 runtime library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true

[dependencies]
ivo-derive.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
