import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar for the "ts" docs plugin instance (versioned - see docusaurus.config.ts).
// Auto-generated from the docs-ts/ (and ts_versioned_docs/version-*/) folder structure.
const sidebars: SidebarsConfig = {
  tsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
