import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Sidebar for the "rs" docs plugin instance (unversioned - latest API only).
// Auto-generated from the docs-rs/ folder structure.
const sidebars: SidebarsConfig = {
  rsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
