name: TS Bun CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.x]

    steps:
      - uses: actions/checkout@v6
      - name: Use Bun.js v${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          version: ${{ matrix.bun-version }}

      - name: 📦 Install dependencies
        run: cd ./ts && bun i

      - name: ⚒️ Build
        run: bun run build

      - name: 🚨 Lint
        run: bun run lint

      - name: 🧪 Test
        run: bun run test
